version: '3'
services:
  auth-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: auth-app
    env_file: .env
    volumes:
      - ./db:/usr/src/app/db
    ports:
      - "8081:8081"